### ISSUE TITLE
React Router pain points

### ISSUE THREAD

**Issue by mjackson** [emmenko/redux-react-router-async-example#10]
This isn't really an issue with your work here. What you've done looks fantastic :) I'm still trying to understand it all, but I was hoping you could help me understand where the React Router API could be better for you to work with.

At React Europe, @gaearon demonstrated how redux lets you really easily do things like record/replay. However, in the 1.0 router API we don't exactly have a clean place for you to record location changes so you can replay them later. Is this a problem for you? If so, what would an ideal API look like for that use case?

I appreciate any knowledge you can share. Thanks!

**Comment by emmenko** [comment]
Hey, thanks but I should be thanking you guys for your amazing work!

Well, to be honest I haven't got much time yet to play around with the 1.0. I mean I've been following the changes and new features etc, but I didn't actually tried them out.
My idea of this repo was also to showcase those cool features step-by-step, in combination with redux. For example the next thing I wanted to do was login using `onEnter` hook.

So I can't tell you much at the moment, when I'm gonna go a bit deeper into the code I can give you more feedback.

In the meantime you can read some threads in the redux repo, talking about integration with RR.

https://github.com/gaearon/redux/issues/227#issuecomment-119237073
https://github.com/gaearon/redux/issues/177

**Comment by mjackson** [comment]
Thanks for the pointers @emmenko! It looks like @acdlite is playing around with our 1.0 API over at https://github.com/acdlite/redux-react-router, so I'm going to follow up on Redux integration there. Again, thanks for your work on this! I hope we can get the integration working really well soon :)
