### ISSUE TITLE
Consider updating to Redux 1.0 RC

### ISSUE THREAD

**Issue by gaearon** [emmenko/redux-react-router-async-example#14]
Redux 1.0 RC is out with breaking changes. **No further API changes are expected in 1.0 so it may be a good time to port the example to 1.0 RC (in a branch).** We will release 1.0 when the docs are ready.

You can find the comprehensive list of the changes in 1.0 RC against 1.0 alpha in the **[Redux 1.0 RC release notes](https://github.com/gaearon/redux/releases/tag/v1.0.0-rc)**. If you haven't ported to alpha yet, you'll need to **[apply changes from 0.12 to alpha first](https://github.com/gaearon/redux/pull/195#issue-92206321)**.

Thank you!
Please make sure to report any issues so we can release a stable 1.0.

**Comment by emmenko** [comment]
Yeah, I'm working on login workflow with the alpha version. Will create a separate PR for the RC. 

Thanks btw, the new API looks really promising!

**Comment by jonaswindey** [comment]
Any news on this, emmenko?

**Comment by emmenko** [comment]
@jonaswindey sorry, being awfully busy lately. The latest changes are in the https://github.com/emmenko/redux-react-router-async-example/pull/11 PR, will try to wrap them up and merge it in the next days.
