### ISSUE TITLE
Add redux-react-router

### ISSUE THREAD

**Issue by jonaswindey** [emmenko/redux-react-router-async-example#25]
It would be great to add https://www.npmjs.com/package/redux-react-router in this project.
That way the current route is also stored in the state, which makes a lot of sense.

**Comment by emmenko** [comment]
Yep, that is something I've been meaning to try. 

Have you successfully used it already?

**Comment by jonaswindey** [comment]
I'm adding it to my project right now. Will keep you updated or propose a pull request.

**Comment by emmenko** [comment]
That would be great, thanks! :)
