### ISSUE TITLE
react-router@1.0.0-rc1 redirectTo becomes replaceState

### ISSUE THREAD

**Issue by eventhough** [emmenko/redux-react-router-async-example#28]
Just a note, when upgrading to react-router@1.0.0-rc1 the `requireAuth()` method for `onEnter` needs to be updated: https://github.com/emmenko/redux-react-router-async-example/blob/master/lib/Root.js#L100

``` javascript
function requireAuth(nextState, replaceState) {
  const state = store.getState();
  const isLoggedIn = Boolean(state.application.credentials);
  if (!isLoggedIn) {
    replaceState({}, '/login', {
      nextPathname: nextState.location.pathname,
    });
  }
}
```

I'm not really sure how to use replaceState. Should we be passing in an empty object, or nextState?

**Comment by emmenko** [comment]
Fixed, thanks!
