### ISSUE TITLE
Upgrade to react-0.14.0

### ISSUE THREAD

**Issue by eriknyk** [emmenko/redux-react-router-async-example#33]
Hi,
would be great if you upgrade your example to react, react-dom 0.14.0, since it was recently released.

Regards.

**Comment by emmenko** [comment]
Will do it as soon as I have some time. Any PR is welcomed of course ;)

**Comment by eyala-stratoscale** [comment]
I issued PR for that  : 
https://github.com/emmenko/redux-react-router-async-example/pull/35
