### ISSUE TITLE
remove i18n ?

### ISSUE THREAD

**Issue by mydearxym** [emmenko/redux-react-router-async-example#38]
amazing work !
it's there a way to remove the i18n support ?  it's just not necessary  for some case .

**Comment by emmenko** [comment]
Glad it helps! :)

What do you mean by removing it? At the end it's just defined in 2 places:
- the components (the default messages)
- the root to wrap the app with the Intl component

I understand that i18n support is not always required but when it is, it's not always easy to set it up. With this I just want to provide an example how you can do that, together with redux.

This example app is meant to showcasing different scenarios that you might find in a web application and how they play nice together. 
If you don't need i18n simply ignore those parts, it should be pretty easy.

Hope this helps :)

**Comment by mydearxym** [comment]
thanks @emmenko 

i just try to make my project simple and small ..
but when i replace all the defineMessages with plain text and change my Root.js parts like this

``` javascript
  // const rootChildren = [
  //   <IntlProvider key="intl" {...intlData}>
  //     {renderRoutes()}
  //   </IntlProvider>
  // ]

  const rootChildren = [
    <div key="renderRoutes">
      {renderRoutes()}
    </div>
  ]
```

i still get this error in my browser: 

``` javascript
[React Intl] Could not find required `intl` object. `IntlProvider` needs to exist in the component ancestry. --------  utils.js?79e7:69 

Uncaught TypeError: Cannot read property 'formatMessage' of undefined   ----- message.js?2bc1
```

**Comment by mydearxym** [comment]
i found a .babelrc.i18n file : 
```javascript
{
  "optional": ["runtime"],
  "stage": 0,
  "plugins": ["react-intl"],
  "extra": {
    "react-intl": {
      "messagesDir": "_translations"
    }
  }
}
```
it's this the reason ?

**Comment by mydearxym** [comment]
sorry i missed a  file , thinks for the hint @emmenko

**Comment by emmenko** [comment]
Cool!

If you need any more help just ask ;)
