### ISSUE TITLE
login set state error 

### ISSUE THREAD

**Issue by mydearxym** [emmenko/redux-react-router-async-example#41]
in [Login.js](https://github.com/emmenko/redux-react-router-async-example/blob/master/lib%2Fcomponents%2Fpages%2FLogin.js#L22)  

``` js
handleInputChange (evt) {
    this.setState({
      [evt.target.name]: evt.target.value
    })
  }
```

evt.target.name gets nothing 

``` js
> evt.target.name 
< ""
```

should be evt.target.type or use refs instead.

**Comment by emmenko** [comment]
Thanks for reporting this!

**Comment by mydearxym** [comment]
@emmenko  you are welcome
