### ISSUE TITLE
Don't work on Safari

### ISSUE THREAD

**Issue by irae** [emmenko/redux-react-router-async-example#47]
`ReferenceError: Can't find variable: Intl`

Maybe use http://formatjs.io instead of babel intl?

**Comment by emmenko** [comment]
Looks like safari is the only browser missing the `Intl` API, thus needs to be polyfill.

See:
- http://formatjs.io/guides/runtime-environments/#client
- https://github.com/andyearnshaw/Intl.js

**Comment by irae** [comment]
Thanks for the fix and inside information on inner workings
