### ISSUE TITLE
IE support ? 

### ISSUE THREAD

**Issue by mydearxym** [emmenko/redux-react-router-async-example#51]
hi @emmenko  
this example seems not work on all version of IE 。 
i checked [here](https://github.com/rackt/redux/issues/1026) and [here](https://github.com/gaearon/react-proxy/issues/27) , these issue may cause the `dev version`(with hot-loader) not work on IE. 

but the `dist version`(without hot-loader) is not work either 。

React  itself support IE8+ ,  is the Redux issue ?

**Comment by emmenko** [comment]
Hey, sorry for the late answer.

Well, to be honest I didn't do any IE compatibility support. Some problems are definitely related to the [lack of IE support of ES6 features](https://babeljs.algolia.com/docs/advanced/caveats/#internet-explorer)  (e.g.: class inheritance, static properties, ...).

For now I don't have any plans on providing IE support, definitely not < IE10 anyway. 

If you do need to support that, I recommend for starters **not** to use classes and static properties, and use the stable `stage` features of babel.
You can also see here the current state of ES6 compatible features. https://kangax.github.io/compat-table/es6/

**Comment by mydearxym** [comment]
@emmenko   thanks for reply , helps me a lot !
