### ISSUE TITLE
Force childs to wait for data updates

### ISSUE THREAD

**Issue by revolunet** [emmenko/redux-react-router-async-example#56]
Hey

I'm playing with this nice boilerplate but i'm a little confused on how to force a child component to wait for some data to be loaded.

In my case, `fetchOnUpdate` doesnt wait for the result before rendering the child.

Should i manually wrap every component into a HoC that toggle the child based on the existence of a desired prop ?

ex :

``` js
render() {
   if (this.props.data) {
        return <ChildComponent {...this.props.data}/>
   } else {
        return <div>Loading...</div>;
   }
}
```

maybe there's any existinsting decorator/HoC that can handle this for me ?

Thanks

**Comment by emmenko** [comment]
Well, react components are basically functions that you call with some props and you get something back. So when the component renders, it doesn't know anything about data fetching and that it needs to "wait for something". This means you always have to rely on the data that you get via props.
In your case yes, you can check `this.props.data` and not render the child component. Then when you fetch the data and the state is updated, the component will re-render with the new props.

Does that help you? :)

**Comment by revolunet** [comment]
Thanks for crystal-clear explanation :+1:

**Comment by emmenko** [comment]
:+1:
